version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: highlights_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d highlights_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  chat_api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # reuse same env as the app service:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
      POSTGRES_DB: ${POSTGRES_DB:-highlights_db}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-004}
      GENERATION_MODEL: ${GENERATION_MODEL:-gemini-1.5-flash}
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: ["bash", "-lc", "uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - chat_api
    ports:
      - "5173:5173"

volumes:
  postgres_data:
